server:
  port: 19091

spring:
  application:
    name: gateway-server
  main:
    web-application-type: reactive
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PW}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-users
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
            - id: user-service-auth
              uri: lb://user-service
              predicates:
                - Path=/api/auth/**
          discovery:
            locator:
              enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_LOCAL_URL}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}