server:
  port: 19091

spring:
  application:
    name: gateway-server
  main:
    web-application-type: reactive
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /api/auth/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_LOCAL_URL}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}